# Generated by Django 5.0 on 2023-12-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro_app', '0005_language_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('actors', models.ManyToManyField(to='intro_app.actor')),
            ],
        ),
    ]
