# Generated by Django 5.0 on 2023-12-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro_app', '0006_actor_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='captial',
            new_name='capital',
        ),
    ]
